apiVersion: v1
kind: Template
metadata:
  name: webspoon-template
  annotations:
    openshift.io/display-name: "Webspoon Pentaho Data Integration"
    openshift.io/documentation-url: "https://github.com/HiromuHota/pentaho-kettle/wiki"
    description: >-
      Spoon tool web version for ETL execution similar to the tool
      desktop Spoon. Preloaded with a series of plugins and example of transformations (kettle files).
      The purpose of this template is exploratory and therefore ephemeral.
labels:
  app: "webspoon"

message: "Enjoy the tool ... Wait a few minutes for it to be ready !!!"

# PARAMETERS
parameters:
  - name: NAME
    description: "App name"
    value: webspoon
    required: true

  - name: GIT_URL
    description: "Repository containing all the artifacts required to run Webspoon in Openshift"
    value: https://github.com/fgomezotero/pentaho-kettle.git
    required: true

objects:

# IMAGESTREAMS
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    dockerImageRepository:

# BUILDCONFIGS
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: webspoon:latest
    source:
      git:
        uri: ${GIT_URL}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: openshift/Dockerfile
      type: Docker
    triggers:
      - type: "ConfigChange"

# DEPLOYMENTCONFIGS
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - image: webspoon
          imagePullPolicy: IfNotPresent
          name: ${NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/tomcat/plugins
              name: ${NAME}-data
              subPath: webspoon/plugins
            - mountPath: /home/tomcat/
              name: ${NAME}-data
              subPath: webspoon/users-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        volumes:
          - name: ${NAME}-data
            persistentVolumeClaim:
              claimName: ${NAME}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: webspoon:latest
      type: ImageChange

# SERVICES
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    sessionAffinity: None
    type: ClusterIP

# ROUTE
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    name: ${NAME}
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None

# PVC
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: openshift-apps